name: project_environment
dependencies:
  - python=3.6.2
  - pip:
    - azureml-defaults==1.0.79
    - azureml-contrib-pipeline-steps
    - interpret
    - azureml-interpret
    - azureml-contrib-interpret
    - scipy==1.2.1
    - scikit-learn==0.20.3
    - joblib==0.13.2
    - pandas==0.25.3
    - numpy==1.16.2
    - inference-schema[numpy-support]