name: aml1.0.79
channels:
  - conda-forge
  - defaults

#azureml-sdk install includes: azureml-core, azureml-dataprep, azureml-train, azureml-train-core, azureml-pipeline, azureml-pipeline-core, azureml-pipeline-steps

dependencies:
- python=3.6.2
- pip
- pip:
  # Azure ML
  - azureml-sdk[explain,automl,notebooks]==1.0.79
  - azureml-dataprep[fuse,pandas]>=1.1.19
  - azureml-monitoring
  - azureml-datadrift
  - azureml-contrib-pipeline-steps
  - interpret
  - azureml-interpret
  - azureml-contrib-interpret
  - azureml-opendatasets
  - azureml-widgets
  - inference-schema[numpy-support]
  # Other
  - jupyter
  - ipywidgets
  - scipy==1.2.1
  - scikit-learn==0.20.3  
  - joblib==0.13.2
  - pandas==0.25.3
  - numpy==1.16.2
  - python-dotenv==0.10.3
  - tqdm==4.36.1
  - matplotlib==3.1.2