parameters:
  rm_service_connection: ''
  resource_group: ''
  workspace: ''
  aks_cluster: ''

jobs:
      - job: CreateAKSCluster
        steps:
          - task: AzureCLI@1
            displayName: 'Install the CLI'
            inputs:
              azureSubscription:  ${{ parameters.rm_service_connection }}
              scriptLocation: inlineScript
              inlineScript: 'az extension add -n azure-cli-ml'

          - task: AzureCLI@1
            displayName: 'Provision AKS Cluster'
            inputs:
              azureSubscription:  ${{ parameters.rm_service_connection }}
              scriptLocation: inlineScript
              inlineScript: 'az ml computetarget create aks --name ${{ parameters.aks_cluster }} --resource-group ${{ parameters.resource_group }} --workspace-name ${{ parameters.workspace }} --cluster-purpose FastProd'